import './globals.css';
// import './index.css';
import { Inter } from 'next/font/google';


import { cookies } from 'next/headers';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { Database } from '../../supabase/types';
import SetProvider from '@/utils/SetProvider';
import { Session } from '@supabase/auth-helpers-nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <SetProvider>
      <html lang='en'>
        <body className={inter.className}>{children}</body>
      </html>
    </SetProvider>
  );
}
